"""Persistent topological naming: a design's names survive regeneration.

Master plan Phase 1.4, and the hard half of the whole kernel. The problem it solves is
what makes conversational CAD fall apart at scale: a feature refers to a face, something
upstream changes, every face id shifts, and the downstream feature lands on the wrong
geometry — or on nothing — without erroring.

The mechanism is OCCT's OCAF `TNaming` framework. A shape is not remembered by index or
by id; it is remembered by **how it came to exist** — this face was generated by that
edge during that fillet — and after a rebuild the same derivation is replayed to find
whatever now plays that role.

Three rules were established by the Phase 1.0 spike. None is obvious, each was got
wrong before it was got right, and breaking any of them produces a naming layer that
*appears* to work and silently resolves to nothing:

**1. One label records one evolution kind.** A `TNaming_Builder` writing both `Modify()`
and `Generated()` onto the same label raises `Standard_ConstructionError: not same
evolution`. A feature's history therefore needs sibling labels. `FeatureLabels` makes
that layout the only one available.

**2. Regeneration must rewrite the same labels.** A name refers to labels in the
document. Rebuilding into fresh labels leaves every selector pointing at the previous
generation's, and `TNaming_Selector.Solve()` then returns **true** while resolving to a
null shape — the worst failure available, because it looks like success. Feature labels
are allocated once and owned for the life of the document.

**3. Edges must be walked, not just faces.** A fillet's new face is `Generated` by the
*edge* that was filleted. Recording only face history leaves that derivation unrecorded
and the name unresolvable after the next rebuild — again with `Solve()` reporting
success. `evolution_of` walks both, and the covering test checks the recovered face's
*area* against a closed-form value so that resolving to the wrong face cannot pass.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from typing import Any

from app.kernel.errors import NamingError
from app.kernel.occt.binding import require, symbol
from app.kernel.occt.topology import edges, faces, shape_list


@dataclass(frozen=True)
class FeatureLabels:
    """The label triple one feature owns for the life of a document.

    Allocated once, rewritten by every regeneration (rule 2). Three labels rather than
    one because a builder may record only one evolution kind (rule 1):

    * `shape` — what this feature produced, as a whole;
    * `modified` — old sub-shape → new sub-shape, for everything it altered;
    * `generated` — source sub-shape → newly created sub-shape, for everything it made.

    A feature that creates from nothing (a primitive) uses `shape` alone. A feature that
    transforms an input (a fillet) uses all three.
    """

    shape: Any
    modified: Any
    generated: Any

    def all(self) -> tuple[Any, Any, Any]:
        return (self.shape, self.modified, self.generated)


def allocate_feature_labels(parent: Any) -> FeatureLabels:
    """Reserve one feature's labels under `parent`. Once per feature, ever."""
    require()
    tags = symbol("TDF_TagSource")
    return FeatureLabels(
        shape=tags.NewChild_s(parent),
        modified=tags.NewChild_s(parent),
        generated=tags.NewChild_s(parent),
    )


def record_primitive(labels: FeatureLabels, shape: Any) -> None:
    """Record a feature that created geometry from nothing."""
    require()
    symbol("TNaming_Builder")(labels.shape).Generated(shape)


def record_derived(
    labels: FeatureLabels,
    *,
    result: Any,
    source: Any,
    modified: Iterable[tuple[Any, Any]] = (),
    generated: Iterable[tuple[Any, Any]] = (),
) -> None:
    """Record a feature that transformed `source` into `result`.

    `modified` and `generated` are (before, after) pairs, written to separate labels
    because OCAF refuses to mix evolutions on one (rule 1).

    A builder is constructed only when there is something for it to write: an empty
    `TNaming_Builder` leaves an attribute claiming an evolution it has no entries for,
    which sends a later `Solve()` down a dead end that it then reports as success.
    """
    require()
    builder = symbol("TNaming_Builder")
    builder(labels.shape).Generated(source, result)

    pairs = list(modified)
    if pairs:
        writer = builder(labels.modified)
        for before, after in pairs:
            writer.Modify(before, after)

    pairs = list(generated)
    if pairs:
        writer = builder(labels.generated)
        for before, after in pairs:
            writer.Generated(before, after)


def evolution_of(maker: Any, source: Any) -> tuple[list[tuple[Any, Any]], list[tuple[Any, Any]]]:
    """Read an OCCT algorithm's history into (modified, generated) pairs.

    Every `BRepBuilderAPI_MakeShape` answers `Modified()` and `Generated()` per input
    sub-shape. Walking the source ourselves — rather than expecting the algorithm to
    volunteer a history — is what makes this uniform across fillet, chamfer, boolean and
    transform, none of which share a history iterator.

    Faces *and* edges are walked (rule 3). Two OCCT calls per sub-shape is the dominant
    cost of recording a feature, and it is the price of names that survive; the shapes
    are gathered once here rather than re-explored per lookup.
    """
    require()
    modified: list[tuple[Any, Any]] = []
    generated: list[tuple[Any, Any]] = []
    for before in (*faces(source), *edges(source)):
        for after in shape_list(maker.Modified(before)):
            modified.append((before, after))
        for after in shape_list(maker.Generated(before)):
            generated.append((before, after))
    return modified, generated


def descendants_of(
    maker: Any, sources: Iterable[Any], *, kind: str = "face"
) -> list[Any]:
    """What each input sub-shape became in the result — master plan 2.2's foundation.

    **`Modified()` returning nothing does not mean the face vanished.** It is OCCT's
    convention for *unchanged*: the face survives into the result as the very same
    `TShape`, and the algorithm has nothing to report about it. `IsDeleted()` is what
    distinguishes the two, and reading `Modified()` alone — which is the obvious way to
    write this — loses every face an operation left alone. On a boss fused to a pad that
    is the cylindrical barrel and the boss top, i.e. the entire feature.

    So the rule is: deleted → nothing; modified → its replacements; otherwise → itself.

    This is what makes `feature#selector` answerable. A feature's own faces are the
    descendants of the shape it contributed — the prism a pad extruded, the tool body a
    boolean added — and they are OCCT's answer rather than a geometric guess about which
    faces look like they belong.

    `kind` casts the results back to `TopoDS_Face` or `TopoDS_Edge`. OCCT's history hands
    back bare `TopoDS_Shape`, and every downstream reader — normals, areas, curvature —
    takes the typed handle and rejects the untyped one, so casting once here beats a cast
    at each of a dozen call sites.
    """
    require()
    cast = _CASTS[kind]

    # **`BRepBuilderAPI_ModifyShape` algorithms answer a different question.**
    # `BRepOffsetAPI_DraftAngle` is one, and its `Modified()` reports only 2 of a box's 6
    # faces after tapering four walls — it under-reports, and reading it alone leaves
    # every earlier feature holding faces the draft has already replaced. Its
    # `ModifiedShape()` answers correctly for all six, because a rebuilt solid gets a new
    # `TShape` for every face whether the geometry changed or not.
    #
    # Only that family exposes `ModifiedShape`, so preferring it where it exists leaves
    # the boolean, fillet and offset paths exactly as they were.
    reshaper = getattr(maker, "ModifiedShape", None)

    found: list[Any] = []
    for source in sources:
        if maker.IsDeleted(source):
            continue
        if reshaper is not None:
            found.append(cast(reshaper(source)))
            continue
        replacements = shape_list(maker.Modified(source))
        found.extend(cast(item) for item in (replacements if replacements else [source]))
    return found


def _face_cast(shape: Any) -> Any:
    return symbol("TopoDS").Face_s(shape)


def _edge_cast(shape: Any) -> Any:
    return symbol("TopoDS").Edge_s(shape)


_CASTS = {"face": _face_cast, "edge": _edge_cast}


def faces_generated_by(maker: Any, source: Any) -> list[Any]:
    """Faces the algorithm *created*, as against ones it merely altered.

    The right answer to "which faces are the fillet's own". A fillet does two things to
    the shape: it **generates** a blend surface from each edge it rounds, and it
    **modifies** the neighbouring faces by trimming them back. Only the first is the
    fillet's own geometry — the trimmed neighbours still belong to whatever built them,
    and claiming them would make `pad#top` and `fillet#top` fight over the same face for
    no benefit.

    Generated results are filtered to faces because `evolution_of`'s walk covers edges
    too, and an edge generated from an edge is not something a face selector can use.
    De-duplicated because one blend face is commonly generated by several edges of a
    tangent chain, and a doubled entry would feed a later operation the same face twice.
    """
    require()
    cast = symbol("TopoDS").Face_s
    face_enum = symbol("TopAbs_ShapeEnum").TopAbs_FACE

    found: list[Any] = []
    for before in (*faces(source), *edges(source)):
        for after in shape_list(maker.Generated(before)):
            if after.ShapeType() != face_enum:
                continue
            if not any(after.IsSame(seen) for seen in found):
                found.append(cast(after))
    return found


def faces_modified_by(maker: Any, source: Any) -> list[Any]:
    """Faces the algorithm altered in place — what a draft contributes.

    Distinct from `faces_generated_by` and the distinction is the point. A draft creates
    no new surface: it tilts walls that already existed. So its contribution is the
    modified set, and the same face is then legitimately claimed by two features — the
    pad that made it and the draft that tapered it. Both statements are true, and
    `pad#...` and `draft#...` both finding it is the honest reading rather than a
    collision to resolve.
    """
    require()
    cast = symbol("TopoDS").Face_s
    face_enum = symbol("TopAbs_ShapeEnum").TopAbs_FACE

    found: list[Any] = []
    for before in faces(source):
        for after in shape_list(maker.Modified(before)):
            if after.ShapeType() != face_enum:
                continue
            if not any(after.IsSame(seen) for seen in found):
                found.append(cast(after))
    return found


def edges_bounding(entities: Iterable[Any]) -> list[Any]:
    """The distinct edges around a set of faces.

    A feature's contributed *edges* are the edges of its contributed faces. Uniform
    across every operation and cheap, where a second history walk would be neither — and
    it gives the answer someone means by "the edges of the boss".
    """
    require()
    cast = symbol("TopoDS").Edge_s
    found: list[Any] = []
    for entity in entities:
        for edge in edges(entity):
            if not any(edge.IsSame(seen) for seen in found):
                found.append(cast(edge))
    return found


def contribution_of(maker: Any, blank: Any) -> tuple[list[Any], list[Any]]:
    """The faces and edges a feature contributed, as (faces, edges).

    Walks the blank's own sub-shapes through the combining algorithm. Faces and edges
    both, for the same reason `evolution_of` walks both (naming rule 3): an edge
    selector on a feature is as reasonable a thing to write as a face one.
    """
    return (
        descendants_of(maker, faces(blank), kind="face"),
        descendants_of(maker, edges(blank), kind="edge"),
    )


class NameRegistry:
    """The design's semantic names, resolvable after any regeneration.

    `app.design.names.SemanticName` gives a design its vocabulary
    (`plate.pivot_bore.inner_face`); this binds each to an OCAF selector, so the name
    still finds the right face after the plate gets thicker. One label per name, reused
    for the life of the document, for the same reason feature labels are (rule 2).
    """

    __slots__ = ("_root", "_selectors")

    def __init__(self, root: Any) -> None:
        require()
        self._root = root
        self._selectors: dict[str, Any] = {}

    def __contains__(self, name: str) -> bool:
        return name in self._selectors

    def __iter__(self) -> Iterator[str]:
        return iter(self._selectors)

    def __len__(self) -> int:
        return len(self._selectors)

    def names(self) -> tuple[str, ...]:
        return tuple(sorted(self._selectors))

    def record(self, name: str, shape: Any, context: Any) -> None:
        """Name `shape`, which must be a sub-shape of `context`.

        Recording an existing name reuses its label — that is a re-record after a
        rebuild, which is correct and required.
        """
        selector = self._selectors.get(name)
        if selector is None:
            label = symbol("TDF_TagSource").NewChild_s(self._root)
            selector = symbol("TNaming_Selector")(label)
            self._selectors[name] = selector

        if not selector.Select(shape, context):
            raise NamingError(
                f"OCCT could not build a persistent name for {name!r}. Either the shape "
                "is not a sub-shape of the context it was given, or the operation that "
                "produced it recorded no history — check that the feature calls "
                "record_derived() with its modified and generated pairs."
            )

    def resolve(self, name: str, valid: Iterable[Any]) -> Any:
        """Find `name` again after a rebuild, against the labels just rewritten.

        `Solve()` returning true is **not** sufficient — it does so even when it
        resolves to nothing — so the result is checked for nullness and a null is an
        error, never an empty answer. That check is the whole reason this wrapper
        exists rather than callers using the selector directly.
        """
        selector = self._selectors.get(name)
        if selector is None:
            known = ", ".join(self.names()) or "nothing"
            raise NamingError(
                f"{name!r} was never recorded, so it cannot be resolved. Recorded: {known}."
            )

        label_map = symbol("TDF_LabelMap")()
        for label in valid:
            label_map.Add(label)

        solved = selector.Solve(label_map)
        shape = symbol("TNaming_Tool").GetShape_s(selector.NamedShape())
        if not solved or shape.IsNull():
            raise NamingError(
                f"{name!r} no longer resolves to any geometry after the rebuild. "
                "Something it depended on was removed or changed shape. Refusing rather "
                "than guessing: a name that silently moves puts the next feature on the "
                "wrong face, which is the failure persistent naming exists to prevent."
            )
        return shape


__all__ = [
    "FeatureLabels",
    "NameRegistry",
    "allocate_feature_labels",
    "evolution_of",
    "record_derived",
    "record_primitive",
]
