"""Error messages, symptoms, and performance -- the things a user reports verbatim.

The entries here are keyed on what the user actually says. `"The selected
element is not connex"` is not a phrase anyone would search for deliberately;
it is a phrase they copy out of a dialog. So the aliases are the message text
in the forms CATIA produces it, and the summary is what it *means*, which is
usually not what it says.

Performance is in the same module because it presents the same way: the user
reports a symptom ("CATIA is slow", "the drawing takes ten minutes"), not a
cause, and the causes are a short, well-known list.
"""

from __future__ import annotations

from app.catia_kb.types import Kind, Section, entry

_D = Kind.DIAGNOSTIC


def _diag(
    key: str,
    name: str,
    aliases: tuple[str, ...],
    summary: str,
    causes: tuple[str, ...],
    fixes: tuple[str, ...],
    *,
    see_also: tuple[str, ...] = (),
    aerospace: str = "",
):
    return entry(
        f"diagnostic.{key}",
        name,
        _D,
        aliases=aliases,
        summary=summary,
        failures=causes,
        fixes=fixes,
        see_also=see_also,
        aerospace=aerospace,
    )


ENTRIES = [
    _diag(
        "open_profile",
        "The pad cannot be created because the profile is open and not limited",
        (
            "profile is open and not limited",
            "the profile is open and not limited",
            "the pad cannot be created",
            "open profile",
            "profile not closed",
            "sketch is not closed",
            "le profil est ouvert",
            "why won't my pad work",
        ),
        "The profile does not enclose an area, and nothing was given to close it against.",
        (
            "Two endpoints that look coincident are a fraction apart",
            "A construction element was left as standard geometry and breaks the chain",
            "The profile is genuinely open by design, and neither Thick nor a limiting face was set",
        ),
        (
            "Tools > Sketch Analysis, Geometry tab: it lists every open profile and offers Close as a corrective action",
            "Add a coincidence constraint at the gap rather than dragging the points together",
            "For a deliberately open profile, tick Thick, or use limits that terminate on real faces",
        ),
        see_also=("sketcher.sketch_analysis", "part_design.pad"),
    ),
    _diag(
        "self_intersecting",
        "The profile is self-intersecting",
        (
            "self intersecting",
            "self-intersecting profile",
            "profile crosses itself",
            "profil auto-intersectant",
            "the sketch crosses itself",
        ),
        "The profile crosses itself, so there is no unambiguous inside.",
        (
            "A spline that loops back on itself",
            "Two sub-profiles that overlap rather than nest",
            "An offset that is larger than a local radius, folding the curve over",
        ),
        (
            "Sketch Analysis reports the intersecting elements",
            "For an offset, reduce it below the smallest radius, or offset in stages",
        ),
        see_also=("sketcher.sketch_analysis",),
    ),
    _diag(
        "not_connex",
        "The selected element is not connex",
        (
            "not connex",
            "the elements are not connex",
            "non connex",
            "cannot create the join",
            "join failed",
            "elements are not adjacent",
        ),
        "The pieces do not touch within the merging distance, so they cannot become one element.",
        (
            "A real gap larger than the merging distance",
            "Surfaces that are near each other but do not share a boundary at all",
            "One element already joined into another, so its boundary is no longer free",
        ),
        (
            "Connect Checker to measure the actual gaps, then set the merging distance to cover them and no more",
            "Healing for gaps too large to merge honestly",
            "Show free edges to see which boundary is not meeting anything",
        ),
        see_also=("gsd.join", "gsd.connect_checker", "gsd.healing"),
    ),
    _diag(
        "update_error",
        "Update Error / the feature cannot be built",
        (
            "update error",
            "feature cannot be built",
            "update diagnosis",
            "erreur de mise a jour",
            "the update failed",
            "red exclamation mark",
            "features went red",
        ),
        "One or more features failed to recompute; the diagnosis dialog lists every one, but usually only the first is a real failure.",
        (
            "A referenced edge or face was regenerated by an upstream change and no longer exists -- topological naming",
            "A dimension change made a feature geometrically impossible (a fillet larger than its face, a shell thicker than a radius)",
            "A broken external link, so the driving geometry is not there at all",
            "A deleted parent whose children were kept",
        ),
        (
            "Work the Update Diagnosis list from the top: fix the first, update again, and most of the rest disappear",
            "Use Parent/Children on the failing feature to see what it actually depended on",
            "Isolate a feature from a lost external reference rather than deleting and re-creating it",
        ),
        see_also=("assembly_design.update", "practice.robust_references", "diagnostic.broken_link"),
    ),
    _diag(
        "broken_link",
        "Broken link / unresolved reference",
        (
            "broken link",
            "unresolved reference",
            "lien rompu",
            "cannot find the document",
            "document not found",
            "the link is broken",
            "missing part in the assembly",
        ),
        "A document points at another that is not where the search order expects it.",
        (
            "A file was moved, renamed, or saved into a different directory than the one it is referenced from",
            "The assembly was sent without its children (no Pack&Go or Send To)",
            "Two documents with the same name in different folders, and the search order found the wrong one",
        ),
        (
            "Edit > Links shows every pointed document and its state; repair the path there",
            "Tools > Options > General > Referenced Documents controls the search order that resolves them",
            "Use Send To > Directory or Pack&Go to move a document set, never a plain file copy",
            "Save Management to see and control where everything is being written",
        ),
        see_also=("data.send_to", "data.search_order", "part_design.copy_paste_special"),
    ),
    _diag(
        "over_constrained",
        "Over-constrained / the constraint is not consistent",
        (
            "over constrained",
            "over-constrained",
            "the constraint is not consistent with the other ones",
            "sur-contraint",
            "too many constraints",
            "cannot add the constraint",
        ),
        "The constraint being added is already implied by the ones present, or contradicts them.",
        (
            "A dimension added where a geometric constraint (symmetry, equality) already fixes the same freedom",
            "A closed dimension chain, where the last dimension is determined by the others",
        ),
        (
            "Set the redundant dimension to reference (driven) so it reports the value without driving it",
            "Delete the geometric constraint if the dimension is the one that should drive",
            "Sketch Analysis, Diagnostic tab, shows the constraint count and the state",
        ),
        see_also=("sketcher.constraint", "practice.fully_constrain"),
    ),
    _diag(
        "under_constrained",
        "Under-constrained sketch",
        (
            "under constrained",
            "under-constrained",
            "sous-contraint",
            "the sketch moves",
            "white geometry",
            "the sketch changed when i edited something else",
        ),
        "The sketch has remaining freedom, so it can move when anything it references changes.",
        (
            "Dimensions were added but the profile was never anchored to the sketch origin",
            "Projected 3D geometry was used as the anchor and the projection moved",
        ),
        (
            "Anchor the profile to the origin (H and V axes) first, then dimension",
            "Sketch Analysis, Diagnostic tab, names how many degrees of freedom remain",
        ),
        see_also=("practice.fully_constrain", "sketcher.sketch_analysis"),
    ),
    _diag(
        "fillet_fails",
        "The fillet cannot be created with the specified radius",
        (
            "fillet cannot be created",
            "fillet failed",
            "the fillet cannot be created with the specified radius",
            "conge impossible",
            "radius too large",
            "my fillet won't work",
        ),
        "The ribbon does not fit somewhere along the chain, or the corner where several ribbons meet cannot be resolved.",
        (
            "The radius exceeds the width of the narrowest adjacent face -- which is often not the face you were looking at",
            "Tangency propagation picked up far more edges than intended, and one of them is the failure",
            "Three or more ribbons meet at a vertex",
            "The fillet is early in the tree and its edge has since been regenerated",
        ),
        (
            "Find *where* it fails before reducing the radius; the narrowest face on the propagated chain sets the ceiling",
            "Switch propagation from Tangency to Minimal",
            "Tick Trim ribbons, and use Blend corner at the failing vertex",
            "Move fillets to the end of the tree",
        ),
        see_also=("part_design.edge_fillet", "practice.fillet_late"),
    ),
    _diag(
        "command_greyed_out",
        "The command is greyed out or the workbench is missing",
        (
            "greyed out",
            "grayed out",
            "command not available",
            "workbench missing",
            "not licensed",
            "no licence",
            "the icon is grey",
            "i can't find the workbench",
            "the toolbar is disabled",
        ),
        "Almost always one of three things: no licence, the wrong workbench, or the wrong thing selected.",
        (
            "The product licence is not held -- the workbench simply is not in the Start menu",
            "The command exists in a different workbench than the one currently active",
            "The command needs a selection or a precondition (no Sheet Metal Parameters, no body in work, nothing selected)",
            "The document is in visualisation mode and cannot be edited",
        ),
        (
            "Check Tools > Options > General > Licensing first -- it is the fastest discriminator",
            "Check what is underlined in the tree (the work object) and what is selected",
            "Switch the component to design mode if it is a cached representation",
        ),
        see_also=("setting.licensing", "licence.tiers", "setting.cache_management"),
    ),
    _diag(
        "corrupt_document",
        "The document is corrupted / unable to load document",
        (
            "unable to load document",
            "document is corrupted",
            "cannot open the file",
            "impossible de charger le document",
            "the file won't open",
            "catia crashed and now it won't open",
        ),
        "The file's internal structure is inconsistent, or it was written by a newer release.",
        (
            "A crash during save",
            "Saved by a more recent release -- V5 has no forward compatibility",
            "Internal errors accumulated over many edits, which is what CATDUA exists for",
        ),
        (
            "Run CATDUA V5 in Check mode, then Clean mode, through the Batch Monitor",
            "Look for the autosave copy in CATTemp before assuming the work is gone",
            "For a newer-release file, the owner must save it down with Downward Compatibility; there is no way to open it in the older release",
        ),
        see_also=("catdua", "setting.catia_environment", "data.downward_compatibility"),
    ),
    _diag(
        "strange_behaviour",
        "CATIA is behaving strangely for no reason in the model",
        (
            "catia is behaving strangely",
            "weird behaviour",
            "toolbars in the wrong place",
            "setting won't stick",
            "catia is acting up",
            "reset catia",
        ),
        "Corrupt or stale user settings, which is a machine problem rather than a document problem.",
        (
            "A .CATSettings file damaged by a crash",
            "Settings written by another release sharing the same settings path",
        ),
        (
            "Close CATIA, rename (do not delete) the CATSettings folder, restart, and let defaults rebuild",
            "Give each installed release its own CATUserSettingPath",
        ),
        see_also=("setting.catsettings", "setting.catia_environment"),
    ),
    _diag(
        "import_not_solid",
        "The imported file came in as surfaces instead of a solid",
        (
            "import is not a solid",
            "step came in as surfaces",
            "no solid after import",
            "imported geometry is not a solid",
            "surfaces instead of a solid",
            "dumb solid",
        ),
        "The exporting system's tolerance was looser than CATIA's, so the faces do not stitch into a closed shell.",
        (
            "IGES, which has no shared topology at all",
            "A STEP written from a system with a coarser modelling tolerance",
            "Genuine gaps in the original model",
        ),
        (
            "Show free edges to see the extent; Connect Checker to size the gaps",
            "Join with a merging distance matched to those gaps, then Healing, then Close Surface",
            "Ask the sender for STEP AP242 from a healed model rather than repairing it every release",
        ),
        see_also=("workflow.import_repair", "format.iges", "gsd.join"),
    ),
    _diag(
        "stress_singularity",
        "The peak stress keeps rising as I refine the mesh",
        (
            "stress singularity",
            "singularity",
            "peak stress at a corner",
            "stress keeps increasing with refinement",
            "hot spot",
            "infinite stress",
            "my factor of safety is tiny at one corner",
        ),
        "A sharp re-entrant corner has no finite elastic stress; refining it makes the number climb forever.",
        (
            "A zero-radius internal corner in the model",
            "A point or edge restraint, which is a singularity by construction",
            "A point load rather than a distributed one",
        ),
        (
            "Refine twice and watch: a real stress converges, a singularity climbs",
            "Model the fillet that exists in the real part, and read the stress there",
            "Restrain and load over areas, not points and edges",
            "Read stress away from the singularity, at the distance the structural method actually calls for",
        ),
        see_also=("gps.precision_error_estimate", "gps.clamp", "workflow.fea"),
    ),
    _diag(
        "assembly_slow",
        "The assembly is slow to open or navigate",
        (
            "assembly is slow",
            "slow to open",
            "catia is slow",
            "big assembly is slow",
            "navigation is jerky",
            "out of memory",
            "performance problem",
        ),
        "Almost always the cache, the display accuracy, or design mode on components nobody is editing.",
        (
            "The cache is off, so every component loads as a full document",
            "The local cache is on a network drive",
            "3D accuracy is set very fine, multiplying triangles across the whole product",
            "Everything is in design mode when only a handful of parts are being edited",
            "Deep contextual link chains, so every update walks the whole product",
        ),
        (
            "Turn the cache on with a local path; use a shared release path for pre-generated CGRs",
            "Open in visualisation mode; switch only the working set to design mode",
            "Loosen 3D accuracy for navigation, and enable occlusion and pixel culling",
            "Selective load, or deactivate the nodes not in play",
            "DMU Optimizer stand-ins for heavy components in a review",
        ),
        see_also=("setting.cache_management", "setting.3d_accuracy", "workflow.large_assembly"),
    ),
    _diag(
        "drawing_slow",
        "Drawing generation takes minutes",
        (
            "drawing is slow",
            "view generation is slow",
            "hidden line removal is slow",
            "drawing takes forever",
            "generative view slow",
        ),
        "Hidden line removal on a large view is the dominant cost, and it re-runs on every change.",
        (
            "Hidden lines on while the layout is still being moved around",
            "3D specifications, threads, centrelines and fillets all generating on every update",
            "Automatic update on, so every small edit regenerates every view",
        ),
        (
            "Switch to manual update while laying out; update once at the end",
            "Turn hidden lines and 3D specifications off until the layout is settled",
            "Use a part-size filter or approximate generation mode for very heavy views",
        ),
        see_also=("drafting.front_view", "drafting.generative_view_style"),
    ),
    _diag(
        "hardware",
        "Graphics corruption, certified drivers and hardware choice",
        (
            "graphics corruption",
            "display artefacts",
            "certified driver",
            "quadro",
            "firepro",
            "radeon pro",
            "opengl",
            "which graphics card",
            "which cpu for catia",
            "hardware recommendation",
        ),
        "V5 is an OpenGL application that is largely single-threaded, so the useful hardware advice is narrow and specific.",
        (
            "A consumer graphics driver rendering incorrectly -- V5 is certified against workstation cards and specific driver revisions",
            "Expecting more cores to help: most interactive V5 operations are single-threaded, so clock speed matters more than core count",
            "A model on a network share, where latency dominates everything else",
        ),
        (
            "Use a certified card and the certified driver revision, not the latest one",
            "Prioritise single-thread clock speed; extra cores help only Photo Studio, some analysis and batch runs",
            "Work on local disk and save to the server, not the other way round",
        ),
        see_also=("setting.3d_accuracy", "diagnostic.assembly_slow"),
    ),
    _diag(
        "version_incompatible",
        "Document created with a more recent version",
        (
            "created with a more recent version",
            "incompatible version",
            "newer release",
            "cannot open a newer file",
            "version incompatible",
            "r30 file in r21",
        ),
        "V5 reads its own release and older ones. It cannot read a newer one, and there is no workaround on the receiving side.",
        (
            "The sender is on a later release",
        ),
        (
            "The sender saves down using downward compatibility, where their release supports the target",
            "Otherwise exchange through STEP AP242, which is release-independent",
        ),
        see_also=("data.downward_compatibility", "format.step"),
    ),
    _diag(
        "not_sufficiently_restrained",
        "The model is not sufficiently restrained / singular stiffness matrix",
        (
            "not sufficiently restrained",
            "singular stiffness matrix",
            "singular matrix",
            "rigid body mode",
            "the analysis won't solve",
            "modele insuffisamment bloque",
        ),
        "The structure can still move as a rigid body, so the stiffness matrix cannot be inverted.",
        (
            "A missing restraint",
            "Restraints that leave a rotation free -- a single coaxial constraint still allows spin",
            "An assembly where two parts have no connection between them at all",
        ),
        (
            "Isostatic Restraint removes exactly the six rigid-body modes and nothing else",
            "Check every part is connected to something: an unconnected part is its own free body",
        ),
        see_also=("gps.clamp", "gas.fastened_connection", "workflow.fea"),
    ),
]

SECTION = Section("troubleshooting", ENTRIES)

__all__ = ["ENTRIES", "SECTION"]
