"""P5.5 approval gates; P5.6 cancellation

Revision ID: 01f9a909fad0
Revises: f9dc89aa8fab
Create Date: 2026-09-10 11:24:27.697521

**`approval_gates` joins the RLS set directly.** It owns an `organisation_id`,
so it takes the same predicate every other tenant table has:
`(tenants IS NULL OR organisation_id = ANY(tenants))`. There is no
unauthenticated reader here — unlike `share_links`, a gate is never resolved by
token — so the permissive-when-unscoped half of that predicate is doing nothing
for this table and is kept only because one shared predicate is what makes the
set reviewable.

**The two `cancel_requested_*` column pairs are nullable with no backfill, and
that is correct.** Null means "nobody has asked this to stop", which is true of
every row that already exists. A default would have had to invent a moment and a
person for runs that finished weeks ago.

**Rollback note.** `downgrade` drops `approval_gates` entirely: every sign-off
ever recorded — who approved what, and the digest of what they were shown — goes
with it, and it is reconstructible from nowhere else. The audit log keeps its
own `gate.decided` entries, which record that a decision happened but not the
evidence the decider was looking at. Dropping the cancellation columns loses who
stopped which run; the run's `cancelled` status survives in `status`, so the
fact of the cancellation does not.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.config import settings

#: Must match `app.core.database.TENANT_SETTING`, as every other copy does.
TENANT_SETTING = "kryova.organisation_ids"

_TENANTS = f"string_to_array(nullif(current_setting('{TENANT_SETTING}', true), ''), ',')"

#: Tables added here that own a tenant column directly.
_TENANT_TABLES: list[str] = ["approval_gates"]

#: Named rather than left to PostgreSQL, so `downgrade` can drop them. The
#: autogenerated version passed `None` to `drop_constraint`, which is a
#: rollback that raises the first time anybody needs it — and the first time
#: anybody needs a rollback is never a convenient one.
_FK_CONVERSATION_CANCELLER = "fk_conversations_cancel_requested_by_id_users"
_FK_SIMULATION_CANCELLER = "fk_simulation_jobs_cancel_requested_by_id_users"


def _predicate(column: str = "organisation_id") -> str:
    return f"({_TENANTS} IS NULL OR {column} = ANY({_TENANTS}))"


def rls_statements(schema: str) -> list[str]:
    """The RLS DDL for a given schema, as executable SQL.

    A function rather than inlined so the isolation test can apply *this* DDL to
    its own schema instead of a hand-copied approximation of it — the reasoning
    every tenant-table migration in this repository records, and which
    `tests/test_tenancy_rls.py` depends on by collecting every migration that
    defines this name.
    """
    statements: list[str] = []
    for table in _TENANT_TABLES:
        qualified = f'"{schema}"."{table}"'
        predicate = _predicate()
        statements += [
            f"ALTER TABLE {qualified} ENABLE ROW LEVEL SECURITY",
            f"ALTER TABLE {qualified} FORCE ROW LEVEL SECURITY",
            f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {qualified}",
            f"CREATE POLICY {table}_tenant_isolation ON {qualified} "
            f"USING {predicate} WITH CHECK {predicate}",
        ]
    return statements


def rls_teardown_statements(schema: str) -> list[str]:
    statements: list[str] = []
    for table in _TENANT_TABLES:
        qualified = f'"{schema}"."{table}"'
        statements += [
            f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {qualified}",
            f"ALTER TABLE {qualified} NO FORCE ROW LEVEL SECURITY",
            f"ALTER TABLE {qualified} DISABLE ROW LEVEL SECURITY",
        ]
    return statements


# revision identifiers, used by Alembic.
revision: str = '01f9a909fad0'
down_revision: Union[str, Sequence[str], None] = 'f9dc89aa8fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'approval_gates',
        sa.Column('organisation_id', sa.String(length=36), nullable=False),
        sa.Column('project_id', sa.String(length=36), nullable=True),
        sa.Column('conversation_id', sa.String(length=36), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('state', sa.String(length=16), nullable=False),
        sa.Column('subject_type', sa.String(length=32), nullable=False),
        sa.Column('subject_id', sa.String(length=64), nullable=False),
        sa.Column('subject_digest', sa.String(length=64), nullable=False),
        sa.Column(
            'evidence',
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
            nullable=False,
        ),
        sa.Column('requested_by_id', sa.String(length=36), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('decided_by_id', sa.String(length=36), nullable=True),
        sa.Column('decision_note', sa.Text(), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        # SET NULL, not CASCADE: deleting the person who approved something must
        # not delete the record that it was approved. The gate loses a name and
        # keeps the decision, which is the honest direction.
        sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_approval_gates_conversation', 'approval_gates', ['conversation_id'], unique=False
    )
    op.create_index(
        'ix_approval_gates_open', 'approval_gates', ['organisation_id', 'state'], unique=False
    )
    op.create_index(
        op.f('ix_approval_gates_organisation_id'),
        'approval_gates',
        ['organisation_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_approval_gates_project_id'), 'approval_gates', ['project_id'], unique=False
    )

    op.add_column(
        'conversations', sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'conversations', sa.Column('cancel_requested_by_id', sa.String(length=36), nullable=True)
    )
    op.create_foreign_key(
        _FK_CONVERSATION_CANCELLER,
        'conversations',
        'users',
        ['cancel_requested_by_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.add_column(
        'simulation_jobs',
        sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        'simulation_jobs', sa.Column('cancel_requested_by_id', sa.String(length=36), nullable=True)
    )
    op.create_foreign_key(
        _FK_SIMULATION_CANCELLER,
        'simulation_jobs',
        'users',
        ['cancel_requested_by_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # SQLite has no row-level security and the offline suite runs on it; the
    # guard is a PostgreSQL one and the database job is where it is enforced.
    if op.get_bind().dialect.name == "postgresql":
        for statement in rls_statements(settings.db_schema):
            op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        for statement in rls_teardown_statements(settings.db_schema):
            op.execute(statement)

    # SQLite cannot drop a named constraint; it also never created one, because
    # `create_foreign_key` on SQLite is a no-op batch operation. Guarding rather
    # than trying and swallowing, so a real failure on PostgreSQL still raises.
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint(_FK_SIMULATION_CANCELLER, 'simulation_jobs', type_='foreignkey')
    op.drop_column('simulation_jobs', 'cancel_requested_by_id')
    op.drop_column('simulation_jobs', 'cancel_requested_at')
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint(_FK_CONVERSATION_CANCELLER, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'cancel_requested_by_id')
    op.drop_column('conversations', 'cancel_requested_at')

    op.drop_index(op.f('ix_approval_gates_project_id'), table_name='approval_gates')
    op.drop_index(op.f('ix_approval_gates_organisation_id'), table_name='approval_gates')
    op.drop_index('ix_approval_gates_open', table_name='approval_gates')
    op.drop_index('ix_approval_gates_conversation', table_name='approval_gates')
    op.drop_table('approval_gates')
