"""P5.3/P5.6 persisted design record

Revision ID: 1ef5f6401c1f
Revises: 01f9a909fad0
Create Date: 2026-09-10 12:41:56.683242

**Neither table joins the RLS set, and that is the consistent choice rather than
an omission.** A design belongs to a *conversation*, and `conversations` and
`conversation_messages` are not tenant-scoped either: a conversation can exist
before a project is chosen, so it has no organisation to be scoped to. Its guard
is `owner_id`, checked in the route, and `design_documents` reaches its owner
through exactly that column. Adding a policy here that scoped on the nullable
`project_id` would either hide every project-less design from its own author, or
— with the usual `IS NULL` escape hatch — protect nothing while looking like it
protected something, which is worse than an honest absence. If conversations
ever gain an organisation, both tables join the set together, in one migration,
against one predicate.

**`revision_number` starts at 1 and the unique constraint on
`(design_id, revision_number)` is the concurrency guard.** Two writers racing to
append revision 4 do not both get it: the second one's INSERT violates the
constraint and fails, rather than silently producing two different revision 4s —
which would make `GET /designs/{id}/diff?from=3&to=4` return whichever the
planner happened to reach first, and would make an approval gate's pinned digest
point at an ambiguous thing.

**Rollback note.** `downgrade` drops both tables, so every revision of every
design goes with them — the parameter history, who moved what, and the digests
approval gates pinned. `approval_gates.subject_digest` survives the drop and
becomes unresolvable: the row still records that somebody approved the design
with digest `abc…` and there is no longer anything with that digest to produce.
Nothing else in the schema holds a spec, so this is not reconstructible from a
backup of another table; it needs a backup of these two.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ef5f6401c1f'
down_revision: Union[str, Sequence[str], None] = '01f9a909fad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_documents',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', name='uq_design_document_conversation')
    )
    op.create_index(op.f('ix_design_documents_conversation_id'), 'design_documents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_design_documents_digest'), 'design_documents', ['digest'], unique=False)
    op.create_index('ix_design_documents_project', 'design_documents', ['project_id'], unique=False)
    op.create_table('design_revisions',
    sa.Column('design_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['design_id'], ['design_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'revision_number', name='uq_design_revision_number')
    )
    op.create_index('ix_design_revisions_design_created', 'design_revisions', ['design_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_design_revisions_design_id'), 'design_revisions', ['design_id'], unique=False)
    op.create_index(op.f('ix_design_revisions_digest'), 'design_revisions', ['digest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_revisions_digest'), table_name='design_revisions')
    op.drop_index(op.f('ix_design_revisions_design_id'), table_name='design_revisions')
    op.drop_index('ix_design_revisions_design_created', table_name='design_revisions')
    op.drop_table('design_revisions')
    op.drop_index('ix_design_documents_project', table_name='design_documents')
    op.drop_index(op.f('ix_design_documents_digest'), table_name='design_documents')
    op.drop_index(op.f('ix_design_documents_conversation_id'), table_name='design_documents')
    op.drop_table('design_documents')
    # ### end Alembic commands ###
