"""initial schema on postgres

Revision ID: 286a04c00025
Revises: 
Create Date: 2026-08-21 18:32:53.315220

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286a04c00025'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('media',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('CAD', 'MESH', 'RESULT_FIELDS', 'VECTOR_INDEX', 'REPORT', 'OTHER', name='mediakind', native_enum=False, length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_kind'), 'media', ['kind'], unique=False)
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index('ix_media_sha256', 'media', ['sha256'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('geometry_versions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_geometry_project_version')
    )
    op.create_index(op.f('ix_geometry_versions_media_id'), 'geometry_versions', ['media_id'], unique=False)
    op.create_index(op.f('ix_geometry_versions_project_id'), 'geometry_versions', ['project_id'], unique=False)
    op.create_table('media_upload_sessions',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('CAD', 'MESH', 'RESULT_FIELDS', 'VECTOR_INDEX', 'REPORT', 'OTHER', name='mediakind', native_enum=False, length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABORTED', name='uploadstatus', native_enum=False, length=16), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('received_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_sha256', sa.String(length=64), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_upload_sessions_expires_at'), 'media_upload_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_media_upload_sessions_owner_id'), 'media_upload_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_upload_sessions_status'), 'media_upload_sessions', ['status'], unique=False)
    op.create_table('simulation_jobs',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('geometry_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('solver', sa.String(length=64), nullable=False),
    sa.Column('load_case', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('element_size_mm', sa.Float(), nullable=True),
    sa.Column('mesh_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fields_media_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fields_media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['geometry_version_id'], ['geometry_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_jobs_geometry_version_id'), 'simulation_jobs', ['geometry_version_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_project_id'), 'simulation_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_simulation_jobs_status'), 'simulation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_jobs_status'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_project_id'), table_name='simulation_jobs')
    op.drop_index(op.f('ix_simulation_jobs_geometry_version_id'), table_name='simulation_jobs')
    op.drop_table('simulation_jobs')
    op.drop_index(op.f('ix_media_upload_sessions_status'), table_name='media_upload_sessions')
    op.drop_index(op.f('ix_media_upload_sessions_owner_id'), table_name='media_upload_sessions')
    op.drop_index(op.f('ix_media_upload_sessions_expires_at'), table_name='media_upload_sessions')
    op.drop_table('media_upload_sessions')
    op.drop_index(op.f('ix_geometry_versions_project_id'), table_name='geometry_versions')
    op.drop_index(op.f('ix_geometry_versions_media_id'), table_name='geometry_versions')
    op.drop_table('geometry_versions')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_media_sha256', table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_index(op.f('ix_media_kind'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
