"""conversation summary facts

Revision ID: 2a00f5443c5f
Revises: 9becb1e46a38
Create Date: 2026-10-04 22:52:28.613056

ROAD_TO_10 2.1.

* `conversations.summary_facts` (nullable text) -- the server's own half of the running
  summary: design parameters, the design's change log and decided sign-offs, read from
  their records at the moment of a fold and frozen beside `summary`. NULL on every
  existing conversation, which is correct: nothing was recorded at their earlier folds, and
  the state block carries the live design regardless.

**Rollback note.** `downgrade` drops the column. A conversation that has folded since the
upgrade loses the frozen facts and carries the model's note alone, exactly as every
conversation did before; nothing else reads it, the design record and the gates it was
read from are untouched, and the next fold writes nothing to a column that no longer exists.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a00f5443c5f'
down_revision: Union[str, Sequence[str], None] = '9becb1e46a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_facts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary_facts')
    # ### end Alembic commands ###
