"""E16.2 conversation task graph

Revision ID: 314c1981036f
Revises: b06890354021

**Nullable with no backfill.** `NULL` means "this conversation declared no
plan", which is true of every row that already exists and of most rows that ever
will: a single part needs no work breakdown, and `plan_work`'s own description
says not to write one for it.

**Stored as a document, not as rows.** `app/ai/taskgraph.py` owns the vocabulary
and validates on load; mirroring tasks and dependencies into tables would be a
second schema that goes stale silently, and nothing ever queries *into* a plan —
it is read whole, by the conversation that owns it.

**Rollback note.** `downgrade` drops the column, so every declared plan goes with
it. What is lost is the ordering and the checkpoints, not the work: the design
record, the operation log and the transcript are all untouched, and an agent
picking the conversation back up would simply have no plan to follow. Approval
gates raised at a checkpoint survive — they are their own table — but the
`evidence.task` id in them becomes unresolvable.
Create Date: 2026-09-10 13:12:08.854891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '314c1981036f'
down_revision: Union[str, Sequence[str], None] = 'b06890354021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('task_graph', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'task_graph')
    # ### end Alembic commands ###
