"""P2.5: share links and project transfers

Revision ID: 40108d7a30d1
Revises: 549ab806da4b
Create Date: 2026-09-10 10:05:52.418116

**`share_links` joins the RLS set; `project_transfers` deliberately does not.**

`share_links` owns an `organisation_id` and gets the same policy every other
tenant table has. That composes with the unauthenticated read route rather than
breaking it, because the shared predicate is
`(tenants IS NULL OR organisation_id = ANY(tenants))` — a request that never
enters a tenant scope, which is exactly what `GET /share/{token}` is, has the
setting unset and the policy passes. RLS is the net under application scoping;
on this table the token is the application scoping.

`project_transfers` reaches its tenant *through the project*, exactly as
`geometry_versions` and `simulation_jobs` do, and gets the same join predicate
the P2 migration already ships. The first draft of this migration left it out on
the grounds that it names two organisations and neither is obviously the owner —
which was the wrong question. The row is history *of a project*, so whoever holds
the project now can read it, and the tenant that gave it away cannot. That is the
same answer the application gives (`OwnedProject`), which is what makes it a net
rather than a second opinion.

**Rollback note.** `downgrade` drops both tables. Every live share link stops
working — which is the safe direction — and the record of which tenants a
project has belonged to is destroyed, which is not recoverable from anywhere
else. The audit log keeps its own `project.transferred` entries.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.config import settings

#: Must match `app.core.database.TENANT_SETTING`, as every other copy does.
TENANT_SETTING = "kryova.organisation_ids"

_TENANTS = f"string_to_array(nullif(current_setting('{TENANT_SETTING}', true), ''), ',')"

#: Tables added here that own a tenant column directly.
_TENANT_TABLES: list[str] = ["share_links"]

#: And those reaching their tenant through `projects`, the P2 pattern.
_VIA_PROJECT_TABLES: list[str] = ["project_transfers"]


def _predicate(column: str = "organisation_id") -> str:
    return f"({_TENANTS} IS NULL OR {column} = ANY({_TENANTS}))"


def _project_predicate(schema: str) -> str:
    return (
        f"({_TENANTS} IS NULL OR EXISTS ("
        f'SELECT 1 FROM "{schema}".projects p '
        f"WHERE p.id = project_id AND p.organisation_id = ANY({_TENANTS})))"
    )


def rls_statements(schema: str) -> list[str]:
    """The RLS DDL for a given schema, as executable SQL.

    A function rather than inlined so an isolation test can apply *this* DDL to
    its own schema instead of a hand-copied approximation of it -- the reasoning
    the P2 and billing migrations both record.
    """
    statements: list[str] = []
    for table, predicate in [
        *((name, _predicate()) for name in _TENANT_TABLES),
        *((name, _project_predicate(schema)) for name in _VIA_PROJECT_TABLES),
    ]:
        qualified = f'"{schema}"."{table}"'
        statements += [
            f"ALTER TABLE {qualified} ENABLE ROW LEVEL SECURITY",
            f"ALTER TABLE {qualified} FORCE ROW LEVEL SECURITY",
            f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {qualified}",
            f"CREATE POLICY {table}_tenant_isolation ON {qualified} "
            f"USING {predicate} WITH CHECK {predicate}",
        ]
    return statements


def rls_teardown_statements(schema: str) -> list[str]:
    statements: list[str] = []
    for table in [*_TENANT_TABLES, *_VIA_PROJECT_TABLES]:
        qualified = f'"{schema}"."{table}"'
        statements += [
            f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {qualified}",
            f"ALTER TABLE {qualified} NO FORCE ROW LEVEL SECURITY",
            f"ALTER TABLE {qualified} DISABLE ROW LEVEL SECURITY",
        ]
    return statements


# revision identifiers, used by Alembic.
revision: str = '40108d7a30d1'
down_revision: Union[str, Sequence[str], None] = '549ab806da4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_transfers',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('from_organisation_id', sa.String(length=36), nullable=False),
    sa.Column('to_organisation_id', sa.String(length=36), nullable=False),
    sa.Column('transferred_by_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transferred_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_transfers_project_id'), 'project_transfers', ['project_id'], unique=False)
    op.create_index('ix_project_transfers_project_time', 'project_transfers', ['project_id', 'created_at'], unique=False)
    op.create_table('share_links',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation', sa.String(length=32), nullable=True),
    sa.Column('allow_geometry_download', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_organisation_id'), 'share_links', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_share_links_project_id'), 'share_links', ['project_id'], unique=False)
    op.create_index('ix_share_links_project_live', 'share_links', ['project_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_share_links_token_hash'), 'share_links', ['token_hash'], unique=True)
    # ### end Alembic commands ###

    # SQLite has no row-level security and the offline suite runs on it; the
    # guard is a PostgreSQL one and the database job is where it is enforced.
    if op.get_bind().dialect.name == "postgresql":
        for statement in rls_statements(settings.db_schema):
            op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        for statement in rls_teardown_statements(settings.db_schema):
            op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_token_hash'), table_name='share_links')
    op.drop_index('ix_share_links_project_live', table_name='share_links')
    op.drop_index(op.f('ix_share_links_project_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_organisation_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('ix_project_transfers_project_time', table_name='project_transfers')
    op.drop_index(op.f('ix_project_transfers_project_id'), table_name='project_transfers')
    op.drop_table('project_transfers')
    # ### end Alembic commands ###
