"""P1: email verification, TOTP second factor, recovery codes

Revision ID: 549ab806da4b
Revises: b941a651831a
Create Date: 2026-09-10 09:34:16.472700

**Existing accounts are backfilled as verified**, and that is a decision rather
than a convenience. Every user in the database predates this column; leaving
them null would refuse project creation to people who already have projects,
which is a regression dressed as a security improvement. Verification exists to
stop *new* sign-ups with addresses nobody owns, and it can only ever mean that.
The backfill stamps `created_at` rather than now(), so the column does not
falsely claim somebody clicked a link today.

**Rollback note.** `downgrade` drops the two tables and the three columns, so
every enrolled second factor and every verification state is destroyed by it —
users who had enrolled would sign in with a password alone afterwards and would
have to enrol again. Nothing else depends on these tables, so the downgrade is
safe in the schema sense; it is the data that does not come back.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549ab806da4b'
down_revision: Union[str, Sequence[str], None] = 'b941a651831a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_codes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash', name='uq_recovery_codes_hash')
    )
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    op.create_index('ix_recovery_codes_user_unused', 'recovery_codes', ['user_id', 'used_at'], unique=False)
    op.create_table('totp_enrolments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('secret_encrypted', sa.String(length=512), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_step', sa.BigInteger(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_totp_enrolments_user')
    )
    op.create_index(op.f('ix_totp_enrolments_user_id'), 'totp_enrolments', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('email_verification_token_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Every account that existed before this column did is verified. See the
    # module docstring: the alternative locks existing users out of their own
    # projects, and verification has never been able to say anything about an
    # address that signed up before it was asked for.
    op.execute(
        sa.text(
            "UPDATE users SET email_verified_at = created_at "
            "WHERE email_verified_at IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_sent_at')
    op.drop_column('users', 'email_verification_token_hash')
    op.drop_column('users', 'email_verified_at')
    op.drop_index(op.f('ix_totp_enrolments_user_id'), table_name='totp_enrolments')
    op.drop_table('totp_enrolments')
    op.drop_index('ix_recovery_codes_user_unused', table_name='recovery_codes')
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    # ### end Alembic commands ###
