"""P5.1 turn event resume buffer

Revision ID: 59af8fd639c6
Revises: 1ef5f6401c1f

**This table is a buffer, not a record, and the retention says so.** Rows live
ten minutes (`app/ai/turn_events.RETENTION_MINUTES`) and are pruned on the write
path, because there is no scheduler in this deployment and a table that only
grows is fine until the day it is not. What actually happened in a conversation
is `conversation_messages`, which is permanent; these rows exist only so a
reader whose stream dropped can rejoin a turn *still running* without waiting
for it to end.

**No RLS, for the same reason `conversations` has none** — a conversation has no
organisation to be scoped to, and its guard is `owner_id` checked in the route.

**Rollback note.** `downgrade` drops the table. Nothing is lost that is not
already in the transcript: at most, readers connected at that instant lose their
place and reload. This is the one table in the schema whose deletion has no
recovery story because it needs none.
Create Date: 2026-09-10 12:54:19.192311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59af8fd639c6'
down_revision: Union[str, Sequence[str], None] = '1ef5f6401c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turn_events',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turn_events_conversation_id'), 'turn_events', ['conversation_id'], unique=False)
    op.create_index('ix_turn_events_created', 'turn_events', ['created_at'], unique=False)
    op.create_index('ix_turn_events_cursor', 'turn_events', ['conversation_id', 'sequence'], unique=True)
    op.create_index(op.f('ix_turn_events_turn_id'), 'turn_events', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_events_turn_id'), table_name='turn_events')
    op.drop_index('ix_turn_events_cursor', table_name='turn_events')
    op.drop_index('ix_turn_events_created', table_name='turn_events')
    op.drop_index(op.f('ix_turn_events_conversation_id'), table_name='turn_events')
    op.drop_table('turn_events')
    # ### end Alembic commands ###
