"""record the solver version that produced a result

Revision ID: 90957dafff41
Revises: 6b877d045c82
Create Date: 2026-09-06 02:53:59.214736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90957dafff41'
down_revision: Union[str, Sequence[str], None] = '6b877d045c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_jobs', sa.Column('solver_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_jobs', 'solver_version')
    # ### end Alembic commands ###
