"""P5.2 simulation stage progress

Revision ID: b06890354021
Revises: 59af8fd639c6

**Nullable with no backfill, and that is correct.** `NULL` means "this run has
not reported where it is", which is true of every row that already exists —
including every finished one, where the status already says what happened. A
default would have had to invent a stage for runs that completed weeks ago.

**Rollback note.** `downgrade` drops the column. Nothing is lost that matters: a
watcher of a run in flight loses the stage line and sees "running", which is the
behaviour this column replaced. No result, no provenance and no billing record
depends on it.
Create Date: 2026-09-10 13:00:34.616898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b06890354021'
down_revision: Union[str, Sequence[str], None] = '59af8fd639c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_jobs', sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_jobs', 'progress')
    # ### end Alembic commands ###
