"""E19.5 the day a design's machine was placed on the market

Revision ID: b5d0e3dae224
Revises: ef4d9b93d3ca

Two nullable columns on `design_documents`: the date the manufacturer records a
unit of the machine was first placed on the market, and who recorded it. Null
is the existing meaning of every row — not recorded — so no backfill is
needed, and no row changes character by being migrated.

**The foreign key is named** so `downgrade` can drop it; an autogenerated
`None` name cannot be dropped on PostgreSQL.

**Rollback note.** `downgrade` drops both columns. The designs and their
revisions survive untouched; what is lost is the recorded placing-on-market
date, so every change afterwards reads as design-time again — the one reading
E19 task 5 exists to stop being given silently. Re-record the dates before
relying on the notice after a rollback.
Create Date: 2026-09-14 17:43:23.814662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d0e3dae224'
down_revision: Union[str, Sequence[str], None] = 'ef4d9b93d3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_FK = "fk_design_documents_placed_on_market_recorded_by"


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('design_documents', sa.Column('placed_on_market_on', sa.Date(), nullable=True))
    op.add_column('design_documents', sa.Column('placed_on_market_recorded_by_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(_FK, 'design_documents', 'users', ['placed_on_market_recorded_by_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(_FK, 'design_documents', type_='foreignkey')
    op.drop_column('design_documents', 'placed_on_market_recorded_by_id')
    op.drop_column('design_documents', 'placed_on_market_on')
