"""simulation thermal case and a nullable load case

A `thermal-conduction` job carries a `ThermalCase` — a conductivity, boundaries and
maybe a volumetric source — and genuinely has **no** mechanical case: no fixture, no
force, no modulus. So `thermal_case` arrives as its own nullable column rather than as
a widened `load_case` (the reason `ThermalCase` is a sibling of `LoadCase` in the first
place: folding them together invites a reader to believe the mechanical loads
influenced the temperature), and `load_case` becomes nullable so such a row does not
have to carry a material and a set of fixtures nobody chose.

**Backwards-compatible in the direction that matters.** Every existing row keeps its
`load_case` and gains a NULL `thermal_case`; nothing is rewritten. The downgrade
restores NOT NULL, which will fail if a conduction job has been written — correctly:
that row has no mechanical case to invent, and inventing one is what the column was
made nullable to avoid.

Revision ID: b941a651831a
Revises: 9b30db1018ad
Create Date: 2026-09-09 10:30:36.660623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b941a651831a'
down_revision: Union[str, Sequence[str], None] = '9b30db1018ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_jobs', sa.Column('thermal_case', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # 'thermal-conduction' is 18 characters and the column was 16. Widened rather
    # than the analysis being renamed to fit: the value is what the API takes and
    # what a reader of the row has to recognise, and 32 leaves room for the next
    # one without another migration.
    op.alter_column('simulation_jobs', 'analysis',
               existing_type=sa.String(length=16),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default='solid')
    op.alter_column('simulation_jobs', 'load_case',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulation_jobs', 'load_case',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('simulation_jobs', 'analysis',
               existing_type=sa.String(length=32),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default='solid')
    op.drop_column('simulation_jobs', 'thermal_case')
    # ### end Alembic commands ###
