"""conversation pin branch rewind

Revision ID: d2ec5f1d8253
Revises: 2a00f5443c5f
Create Date: 2026-10-04 23:18:21.829271

ROAD_TO_10 2.5 and 2.6.

* `conversations.pinned_at` -- a pinned conversation sorts to the top of the sidebar; NULL is
  "not pinned". Setting it does not move `updated_at`.
* `conversations.branched_from_id` (nullable, self-referencing, SET NULL, indexed) and
  `branched_at_sequence` -- where a branch came from and the last message it took.
* `conversations.rewound_at` -- when the newest messages were last rewound for a retry or an
  edit; a turn recorded before it is not continuable.

Existing rows keep NULL in all four, which is correct for each: nothing was pinned, branched
or rewound before this existed.

**Rollback note.** `downgrade` drops all four columns, the index and the foreign key. Pins are
lost (every conversation unpins), a branch forgets which conversation it came from and the
message it started at (the copied messages themselves stay: they are ordinary messages of the
branch), and `rewound_at` is forgotten, so a turn that was rewound past could be offered a
Continue again until the next turn is recorded. No message, design or ledger row is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ec5f1d8253'
down_revision: Union[str, Sequence[str], None] = '2a00f5443c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('branched_from_id', sa.String(length=36), nullable=True))
    op.add_column('conversations', sa.Column('branched_at_sequence', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('rewound_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_conversations_branched_from_id'), 'conversations', ['branched_from_id'], unique=False)
    op.create_foreign_key(
        'conversations_branched_from_id_fkey',
        'conversations',
        'conversations',
        ['branched_from_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_branched_from_id_fkey', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_branched_from_id'), table_name='conversations')
    op.drop_column('conversations', 'rewound_at')
    op.drop_column('conversations', 'branched_at_sequence')
    op.drop_column('conversations', 'branched_from_id')
    op.drop_column('conversations', 'pinned_at')
    # ### end Alembic commands ###
