"""P4.1 attachments as first-class objects

Revision ID: ef4d9b93d3ca
Revises: 753d57fdd4bb

**No RLS, matching `conversations` and `design_documents`.** An attachment
belongs to a conversation, which has no organisation to be scoped to, and its
guard is `owner_id` checked in the route. `project_id` is nullable — a file can
be attached before a project is chosen — so a policy keyed on it would either
hide every project-less attachment from its own author or, with the usual
`IS NULL` escape, protect nothing while looking like it protected something.

**`media_id` is RESTRICT, matching `geometry_versions`.** A blob under an
attachment must not be deleted out from under the citations that point into it.
`conversation_id` and `project_id` are CASCADE, which is the *opposite* of
`ai_token_usage`'s SET NULL and deliberately so: spend outlives the conversation
that incurred it, an attachment does not — it has no meaning outside the
conversation it was handed to.

**Rollback note.** `downgrade` drops the table. Every blob survives, because it
lives in the content-addressed store and this table only points at it; what is
lost is *why* each blob was uploaded, what was read out of it, and the citations
in any design parameter that name an `attachment_id`. Those citations become
unresolvable strings — they still say "cell C7 of loads.xlsx", which remains
true and readable, but nothing can navigate back to the file.
Create Date: 2026-09-10 13:30:21.359550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef4d9b93d3ca'
down_revision: Union[str, Sequence[str], None] = '753d57fdd4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('detected_kind', sa.String(length=32), nullable=False),
    sa.Column('detected_format', sa.String(length=32), nullable=False),
    # `EnumText` in the model, plain VARCHAR here. Autogenerate renders it as
    # `app.models.types.EnumText(length=16)` — a name the migration does not
    # import (so it fails on the way up) and which would lose the enum class
    # even if it did. `EnumText` emits exactly this DDL, which is why adopting
    # it anywhere needs no migration and `alembic check` stays clean.
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reader', sa.String(length=32), nullable=False),
    sa.Column('reliability', sa.String(length=16), nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_conversation_created', 'attachments', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_attachments_conversation_id'), 'attachments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_attachments_media_id'), 'attachments', ['media_id'], unique=False)
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_index('ix_attachments_owner_media', 'attachments', ['owner_id', 'media_id'], unique=False)
    op.create_index(op.f('ix_attachments_project_id'), 'attachments', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_project_id'), table_name='attachments')
    op.drop_index('ix_attachments_owner_media', table_name='attachments')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_media_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_conversation_id'), table_name='attachments')
    op.drop_index('ix_attachments_conversation_created', table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
