"""P3: account lifecycle, feature flags, announcements, maintenance

**None of these tables is tenant-scoped, and that is correct rather than an
omission.** `feature_flags`, `announcements` and `maintenance_windows` are
platform state: they describe the deployment, not a customer's work, and every
tenant sees the same rows. `feature_flag_overrides` names a tenant but is
written and read only by staff through `/admin`, and putting it inside the RLS
net would hide an override from the console that set it — the console runs with
the staff member's own (usually empty) tenant context.

**Rollback note.** `downgrade` drops the three tables and the six user columns.
An in-flight maintenance window would end (safe: mutations resume), every flag
and override is lost (features fall back to whatever the code defaults to, so
check those before rolling back a release that added one), and any *scheduled
deletion* is forgotten — which fails safe, since nothing is erased, but the
requests would have to be made again.

Revision ID: f9dc89aa8fab
Revises: 40108d7a30d1
Create Date: 2026-09-10 10:28:51.995261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dc89aa8fab'
down_revision: Union[str, Sequence[str], None] = '40108d7a30d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('killed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_feature_flags_key')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=False)
    op.create_table('announcements',
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcements_window', 'announcements', ['starts_at', 'ends_at'], unique=False)
    op.create_table('feature_flag_overrides',
    sa.Column('feature_flag_id', sa.String(length=36), nullable=False),
    sa.Column('organisation_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_flag_id', 'organisation_id', name='uq_flag_override_org'),
    sa.UniqueConstraint('feature_flag_id', 'user_id', name='uq_flag_override_user')
    )
    op.create_index('ix_flag_overrides_flag', 'feature_flag_overrides', ['feature_flag_id'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_staff', sa.Boolean(), nullable=False),
    sa.Column('started_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('suspended_by_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deletion_requested_by_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['suspended_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['deletion_requested_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deletion_requested_by_id')
    op.drop_column('users', 'deletion_requested_at')
    op.drop_column('users', 'deletion_scheduled_at')
    op.drop_column('users', 'suspended_by_id')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'suspended_at')
    op.drop_table('maintenance_windows')
    op.drop_index('ix_flag_overrides_flag', table_name='feature_flag_overrides')
    op.drop_table('feature_flag_overrides')
    op.drop_index('ix_announcements_window', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
